runtime: custom
env: flex

# This sample incurs costs to run on the App Engine flexible environment. 
# The settings below are to reduce costs during testing and are not appropriate
# for production use. For more information, see:
# https://cloud.google.com/appengine/docs/flexible/python/configuring-your-app-with-app-yaml
automatic_scaling:
  max_num_instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

skip_files:
- imagenet/tf_files/

network:
  forwarded_ports:
    - 80:8080/tcp